### ISSUE TITLE
Data display (Part 2)

### ISSUE THREAD

**Issue by lziegler08** [lziegler08/COVID_dash#3]
Part 2: Data display
In this phase, you will focus on the User Interface of your project. Bokeh is a data visualization library in Python. It provides highly interactive graphs and plots. What makes it different from other Python plotting libraries is that the output from Bokeh will be on the web page, meaning if we run the code in python editor the resulting plot will be in the browser. This gives the advantage of embedding the Bokeh plot on any website. You are encouraged to use HTML features for creating pop-up and pull-down menus, value lists, input/output forms, labels and customized reports, and in the process come up with a system that caters to users with only limited computer knowledge. We don’t care about having a beautiful UI. It only has to work!

**Comment by claireticknor** [comment]
Bokeh: useful options/initial findings

- bokeh.models HoverTool
- bokeh.layouts
- bokeh.plotting

- To save as an HTML:
output_file(filename="file name.html", title = "COVID Dash")
save()

- To use dictionary data (not sure about JSON):
from bokeh.models import ColumnDataSource
source = ColumnDataSource(data = data)
p = figure()
p.circle(x='x_values', y='y_values', source = source)

- Interactive:
[https://docs.bokeh.org/en/2.4.2/docs/user_guide/interaction/widgets.html](url)
